# Generated by Django 5.2.1 on 2025-05-21 05:09

import django.db.models.deletion
import scan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('filesize', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('img_base64', models.TextField()),
                ('model_result', models.JSONField(default=scan.models.model_result_default)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
